kafka:
  pool: nav-prod
soknadsdialogens_url: https://www.nav.no/dagpenger/dialog
brukerdialog_url: https://brukerdialog-dagpenger.nav.no
kafka_extra_topic: teamarenanais.gg-arena-vedtak-dagpenger-v2-p, min-side.aapen-varsel-hendelse-v1
