apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-varsel
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: "{{image}}"
  kafka:
    pool: "{{kafka.pool}}"
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: dp-varsel
    - name: KAFKA_RAPID_TOPIC
      value: teamdagpenger.rapid.v1
    - name: KAFKA_RESET_POLICY
      value: earliest
    - name: BRUKERVARSEL_TOPIC
      value: min-side.aapen-brukervarsel-v1
    - name: SOKNADSDIALOGENS_URL
      value: "{{soknadsdialogens_url}}"
    - name: TMS_UTKAST_TOPIC
      value: min-side.aapen-utkast-v1
    - name: KAFKA_EXTRA_TOPIC
      value: "{{kafka_extra_topic}}"
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  gcp:
    sqlInstances:
      - name: dp-varsler
        type: POSTGRES_14
        tier: db-custom-1-3840
        cascadingDelete: false
        collation: nb_NO.UTF8
        autoBackupHour: 1
        databases:
          - envVarPrefix: DB
            name: varsler
        diskAutoresize: true
        diskSize: 10
        diskType: SSD
        highAvailability: true
        pointInTimeRecovery: true
        retainedBackups: 14
  filesFrom:
    - secret: brukernotifikasjon-broadcast-beskjed
      mountPath: /var/run/secrets/brukernotifikasjon-broadcast-beskjed
  replicas:
    min: 2
    max: 2
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
