apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-varsel
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{image}}
  kafka:
    pool: {{kafka.pool}}
  secureLogs:
    enabled: true
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: dp-varsel
    - name: KAFKA_RAPID_TOPIC
      value: teamdagpenger.rapid.v1
    - name: KAFKA_RESET_POLICY
      value: earliest
    - name: BRUKERNOTIFIKASJON_BESKJED_TOPIC
      value: min-side.aapen-brukernotifikasjon-beskjed-v1
    - name: BRUKERNOTIFIKASJON_OPPGAVE_TOPIC
      value: min-side.aapen-brukernotifikasjon-oppgave-v1
    - name: BRUKERNOTIFIKASJON_DONE_TOPIC
      value: min-side.aapen-brukernotifikasjon-done-v1
    - name: SOKNADSDIALOGENS_URL
      value: {{soknadsdialogens_url}}
    - name: TMS_UTKAST_TOPIC
      value: min-side.aapen-utkast-v1
  gcp:
    sqlInstances:
      - name: dp-varsler
        type: POSTGRES_14
        tier: db-custom-1-3840
        cascadingDelete: false
        collation: nb_NO.UTF8
        autoBackupHour: 1
        databases:
          - envVarPrefix: DB
            name: varsler
        diskAutoresize: true
        diskSize: 10
        diskType: SSD
        highAvailability: true
        pointInTimeRecovery: true
        retainedBackups: 14
  filesFrom:
    - secret: brukernotifikasjon-broadcast-beskjed
      mountPath: /var/run/secrets/brukernotifikasjon-broadcast-beskjed
      optional: true
  replicas:
    min: 2
    max: 2
